# Generated by Django 5.2.17 on 2026-09-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.CharField(max_length=100)),
                ('measurable_item', models.CharField(max_length=100)),
                ('validity', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('computable_days', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('version_parameter', models.CharField(max_length=10)),
                ('minimum_threshold', models.IntegerField()),
                ('maximum_computable_days', models.IntegerField()),
                ('semaphore', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target_value', models.CharField(max_length=100)),
                ('unity', models.CharField(max_length=50)),
                ('goal_value', models.FloatField()),
                ('validity', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.position')),
                ('measuring', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.measuring')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.period')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
