# Generated by Django 5.2.17 on 2026-09-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('application', models.CharField(max_length=100)),
                ('taken_action', models.TextField()),
                ('name_contact', models.CharField(max_length=70)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('state_validity', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('date_evidence', models.DateField()),
                ('metadata', models.CharField(max_length=500)),
                ('validity_state', models.CharField(max_length=20)),
                ('date_validity', models.DateField()),
                ('observations_validity', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
