# Generated by Django 5.2.17 on 2026-09-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('agenda', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='agenda.commitment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='functionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.functionary'),
        ),
    ]
