# Generated by Django 5.2.17 on 2026-09-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_initial'),
        ('configuration', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='measuring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.measuring'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='funcionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences_uploaded', to='personal.functionary'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='verificator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidences_verified', to='personal.functionary'),
        ),
    ]
