# Generated by Django 5.2.17 on 2026-10-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='date_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='observations_validity',
            field=models.TextField(blank=True),
        ),
    ]
