# Generated by Django 5.2.17 on 2026-09-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('applic_name', models.CharField(max_length=70)),
                ('territory', models.CharField(max_length=60)),
                ('commitment_date', models.DateField()),
                ('support', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('JOINED', 'Joined'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='JOINED', max_length=20)),
                ('observation', models.CharField(blank=True, max_length=300)),
                ('functionary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='personal.functionary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
