# Generated by Django 5.2.17 on 2026-09-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='measuring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='configuration.measuring'),
        ),
    ]
