# Generated by Django 5.2.17 on 2026-10-01 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('configuration', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitment',
            options={'ordering': ['commitment_date']},
        ),
        migrations.AlterField(
            model_name='commitment',
            name='measuring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='configuration.measuring'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['state', 'commitment_date'], name='agenda_comm_state_6e9ac9_idx'),
        ),
    ]
